services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: citizen_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d citizen_db -h localhost -p 5432"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  server:
    image: server
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: citizen_db
      DB_SSL: "false"
    ports:
      - "5000:5000"
      - "9229:9229"
    command: ["node", "--inspect=0.0.0.0:9229", "src/index.js"]
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
